channels:
  - conda-forge
  - dlr-sc
  - pythonocc 
  - oce
  - tpaviot
dependencies:
  - python=3.7
  - numpy
  - mesa-libgl-cos6-x86_64
  - mesa-libgl-devel-cos7-ppc64le
  - pythonocc-core=7.5.1
  - pythreejs
  - smesh
  - pip
  - pip:
    - pandas
    - matplotlib

