#!/bin/sh

apt-get -qq update 
apt-get install --yes --no-install-recommends apt-transport-https 
apt-get install --yes --no-install-recommends libgl1-mesa-glx 
apt-get install --yes --no-install-recommends libglu1-mesa 
apt-get -qq purge 
apt-get -qq clean 
rm -rf /var/lib/apt/lists/*
